// <auto-generated />
namespace NextFlicksMVC4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddOmdbContextProper : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOmdbContextProper));
        
        string IMigrationMetadata.Id
        {
            get { return "201301081723398_AddOmdbContextProper"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
